---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: aquasec/scanner-cli
    tag: 3.2
    username: ((mustafaatakan-username))
    password: ((mustafaatakan-passwd))

inputs:
  - name: github.com_matakan_hello_hapi
  - name: docker-push

run:
  path: github.com_matakan_hello_hapi/ci/scripts/run_security_scan.sh
