---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: github.com_matakan_hello_hapi
  - name: dependency-cache

run:
  path: github.com_matakan_hello_hapi/ci/scripts/run_tests.sh
