---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: {{.Release.Name}}-demo-cicd
  labels:
    app: {{.Release.Name}}-demo-cicd
spec:
  replicas: 3
  revisionHistoryLimit: 2
  template:
    metadata:
      namespace: default
      labels:
        app: {{.Release.Name}}-demo-cicd
    spec:
      containers:
        - name: {{.Release.Name}}-demo-cicd
          image: mustafaatakan/demo-cicd:latest
          imagePullPolicy: Always
