---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: {{.Release.Name}}-demo-cicd-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{.Release.Name}}-demo-cicd
  type: LoadBalancer
